name: A workflow to get some GitHub action
on: push

jobs:
  build:
    name: Get some github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ../../action/
        with:
          MESSAGE: "GOT SOME GITHUB ACTION"
